export const FUTURE_QUOTES: readonly string[] = [
  "The future is not a place you can live in.",
  "You can visit the future. You cannot live there.",
  "Nothing you are imagining is happening. This is.",
  "The life you are picturing only exists in your head.",
  "Only this moment is real. Everything else is a story.",
  "No one has ever lived in tomorrow.",
  "The future is made of nows. This is one.",
  "When you get there, it will just be another now.",
  "Tomorrow never arrives the way you pictured it.",
  "You are rehearsing a day that will not go the way you imagine.",
  "There is no point waiting for a life to start. This is it.",
  "Imagining it is not the same as building it.",
  "The thought is not the thing.",
  "Your future is built by what your hands do next.",
  "The next small thing you do is worth more than the whole daydream.",
  "You are not late. You are just somewhere else in your head.",
  "The mind travels. The body stays. Come back to where it is.",
  "This is the only moment you will ever get to act in.",
  "Even the best future will be lived as a present.",
  "You are borrowing joy from a day that has not happened.",
  "You cannot enjoy a moment you are not in.",
  "The future is not waiting for your daydream. It is waiting for your work.",
  "There is no version of the future that skips the present.",
  "You are not there yet, and that is fine. Be here.",
  "A thought about the future is only a thought.",
  "The imagined win gives you nothing. The next step gives you something.",
  "The imagined version is always brighter. The real one is the only one you can touch.",
  "The future you see is edited. The present is unedited, and it is yours.",
  "You will never meet the person you are imagining. You can only be who you are now.",
  "Right now is the only time anything has ever happened.",
  "Nobody has ever actually left. You are still exactly where you were.",
  "Your body has not moved. Notice where it is.",
  "Look around. This room is real.",
  "Feel your feet. That is where you are.",
  "Take one breath. The future can wait one breath.",
  "Whatever you imagine, you are still sitting where you were.",
  "The version of you in that future is built by the version of you here.",
  "This is not a waiting room. This is the life.",
  "Be where your hands are.",
  "The thought will keep. This moment will not.",
  "Nothing in that future can be done from here, except the next step.",
  "You cannot spend a single minute of tomorrow today.",
  "The future will ask for the same thing the present does: your attention.",
  "Every future you imagine is waiting on something you do today.",
  "Stay as long as you like. It will still only be a thought.",
];

// Picks a random line, never the same one as `previous`.
export function pickFutureQuote(previous?: string): string {
  const pool = FUTURE_QUOTES.filter((quote) => quote !== previous);
  const index = Math.floor(Math.random() * pool.length);
  return pool[index] ?? FUTURE_QUOTES[0] ?? "";
}